services:
  stonk-bot:
    image: ghcr.io/whyzotee/stonk-bot:latest
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
    volumes:
      - stonk_data:/app/data
    restart: unless-stopped

volumes:
  stonk_data: